version: '3.7'

services:
  bitrix: &default
    build: &build
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - mysql
    tty: true
    volumes:
      - ./docker/configs/.settings.php:/var/www/html/bitrix/.settings.php
      - ./docker/configs/dbconn.php:/var/www/html/bitrix/php_interface/dbconn.php
      - ./begateway.erip:/var/www/html/bitrix/modules/begateway.erip

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sitemanager
