version: '3.7'

services:
  bitrix: &default
    build: &build
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - mysql
    tty: true
    volumes:
      - ./docker/configs/.settings.php:/var/www/html/bitrix/.settings.php
      - ./docker/configs/dbconn.php:/var/www/html/bitrix/php_interface/dbconn.php
      #- ./.last_version/begateway.payment:/var/www/html/bitrix/modules/begateway.payment
      #- ./.last_version/begateway.payment/install/php_interface/include/sale_payment/begateway:/var/www/html/bitrix/php_interface/include/sale_payment/begateway
      #- ./.last_version/begateway.payment/install/admin/begateway_adminbutton.php:/var/www/html/bitrix/admin/begateway_adminbutton.php
      #- ./.last_version/begateway.payment/install/front/lang:/var/www/html/begateway/lang
      #- ./.last_version/begateway.payment/install/front/pay.php:/var/www/html/begateway/pay.php

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sitemanager
